/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBTables.TableINF;
import DBTables.UOM;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MR
 */
public class DefineUOM extends javax.swing.JFrame {

    /**
     * Creates new form DefineUOM
     */
    UOM uom ;
    String UOMSelected , SymbolSelected;
    TableINF inf;
    
    public DefineUOM() throws Exception {
        initComponents();
        uom = new UOM();
        uom.Show_user_inTable(Table_UOM);
        inf = new TableINF();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_add = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_Update = new javax.swing.JButton();
        tx_symbol = new javax.swing.JTextField();
        tx_UOM1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_UOM = new javax.swing.JTable();

        setTitle("تعري وحدات");
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("إسم الوحدة");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("الرمز");

        bt_add.setBackground(new java.awt.Color(255, 102, 51));
        bt_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_add.setText("إضافة وحدة");
        bt_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addMouseClicked(evt);
            }
        });

        bt_delete.setBackground(new java.awt.Color(255, 102, 51));
        bt_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_delete.setText("حذف وحدة");
        bt_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_deleteMouseClicked(evt);
            }
        });

        bt_Update.setBackground(new java.awt.Color(255, 102, 51));
        bt_Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_Update.setText("تعديل وحدة");
        bt_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_UpdateMouseClicked(evt);
            }
        });

        tx_symbol.setBackground(new java.awt.Color(108, 122, 137));
        tx_symbol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_symbol.setForeground(new java.awt.Color(255, 255, 255));
        tx_symbol.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tx_UOM1.setBackground(new java.awt.Color(108, 122, 137));
        tx_UOM1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_UOM1.setForeground(new java.awt.Color(255, 255, 255));
        tx_UOM1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_UOM1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_symbol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(bt_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_add)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_UOM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tx_symbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_add)
                    .addComponent(bt_delete)
                    .addComponent(bt_Update))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel2);

        Table_UOM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_UOM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الرمز", "إسم الوحدة", "م"
            }
        ));
        Table_UOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_UOMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_UOM);
        if (Table_UOM.getColumnModel().getColumnCount() > 0) {
            Table_UOM.getColumnModel().getColumn(2).setPreferredWidth(15);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addMouseClicked
        actionAddSelected();
    }//GEN-LAST:event_bt_addMouseClicked

    private void Table_UOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_UOMMouseClicked
        actionTableSelected();
    }//GEN-LAST:event_Table_UOMMouseClicked

    
    private void bt_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_UpdateMouseClicked
        actionUpdate();
    }//GEN-LAST:event_bt_UpdateMouseClicked

    private void bt_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_deleteMouseClicked
        try {
            actionDeleteSelected();
        } catch (Exception ex) {
            Logger.getLogger(DefineUOM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_deleteMouseClicked

    public void actionUpdate(){
        try {
           int ID= inf.getIDForTRX("UOM",UOMSelected);
            uom.updateUOM(tx_symbol.getText().toString(), tx_symbol.getText().toString(), ID, Table_UOM);
        } catch (Exception ex) {
            Logger.getLogger(DefineUOM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void actionTableSelected(){
          int row = Table_UOM.getSelectedRow();
       this.tx_symbol.setText( Table_UOM.getModel().getValueAt(row, 1).toString());
       this.UOMSelected =Table_UOM.getModel().getValueAt(row, 1).toString();
       this.tx_symbol.setText( Table_UOM.getModel().getValueAt(row, 0).toString());
       this.SymbolSelected = Table_UOM.getModel().getValueAt(row, 0).toString();
    }
    
    
    public void actionAddSelected(){
         try {
            uom.addUOM(tx_symbol, tx_symbol, Table_UOM);
            tx_symbol.setText("");
            tx_symbol.setText("");
        } catch (Exception ex) {
            Logger.getLogger(DefineUOM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void actionDeleteSelected() throws SQLException, Exception{
         int ID= inf.getIDForTRX("UOM",UOMSelected);
         uom.DeleteUOM(ID, Table_UOM);
     }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefineUOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefineUOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefineUOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefineUOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DefineUOM().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DefineUOM.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_UOM;
    private javax.swing.JButton bt_Update;
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tx_UOM1;
    private javax.swing.JTextField tx_symbol;
    // End of variables declaration//GEN-END:variables
}
