/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBTables.Employee;
import DBTables.TableINF;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MR
 */
public class DefineEmployee extends javax.swing.JFrame {

    /**
     * Creates new form DefineEmployee
     */
    TableINF inf;
    Employee emp;
    String name;
    public DefineEmployee() throws Exception {
        initComponents();
        emp = new Employee();
        inf = new TableINF();
        this.setLocationRelativeTo(null);
        this.setSize(700, 600);
        emp.Show_user_inTable(jTable_employee);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tx_age = new javax.swing.JTextField();
        tx_name = new javax.swing.JTextField();
        tx_adress = new javax.swing.JTextField();
        tx_phone = new javax.swing.JTextField();
        tx_email = new javax.swing.JTextField();
        bt_update = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_add1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_employee = new javax.swing.JTable();

        setTitle("تعريف الموظفين");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("الإسم");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("السن");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("رقم الموبايل");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("البريد الإلكتروني");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("العنوان");

        tx_age.setBackground(new java.awt.Color(108, 122, 137));
        tx_age.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_age.setForeground(new java.awt.Color(255, 255, 255));
        tx_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tx_name.setBackground(new java.awt.Color(108, 122, 137));
        tx_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_name.setForeground(new java.awt.Color(255, 255, 255));
        tx_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tx_adress.setBackground(new java.awt.Color(108, 122, 137));
        tx_adress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_adress.setForeground(new java.awt.Color(255, 255, 255));
        tx_adress.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tx_phone.setBackground(new java.awt.Color(108, 122, 137));
        tx_phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_phone.setForeground(new java.awt.Color(255, 255, 255));
        tx_phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tx_email.setBackground(new java.awt.Color(108, 122, 137));
        tx_email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_email.setForeground(new java.awt.Color(255, 255, 255));
        tx_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bt_update.setBackground(new java.awt.Color(255, 102, 51));
        bt_update.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_update.setText("تعديل");
        bt_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_updateMouseClicked(evt);
            }
        });

        bt_add.setBackground(new java.awt.Color(255, 102, 51));
        bt_add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_add.setText("إضافة");
        bt_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addMouseClicked(evt);
            }
        });

        bt_delete.setBackground(new java.awt.Color(255, 102, 51));
        bt_delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_delete.setText("حذف");
        bt_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_deleteMouseClicked(evt);
            }
        });

        bt_add1.setBackground(new java.awt.Color(255, 102, 51));
        bt_add1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_add1.setText("إعادة إدخال");
        bt_add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_add1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_add1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tx_age, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_name, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_email, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tx_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tx_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tx_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tx_adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(bt_add1)
                        .addGap(18, 18, 18)
                        .addComponent(bt_add)
                        .addGap(18, 18, 18)
                        .addComponent(bt_update)
                        .addGap(18, 18, 18)
                        .addComponent(bt_delete)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jTable_employee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "البريد الإلكتروني", "رقم الموبايل", "العنوان", "السن", "الإسم", "م"
            }
        ));
        jTable_employee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_employeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_employee);
        if (jTable_employee.getColumnModel().getColumnCount() > 0) {
            jTable_employee.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable_employee.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable_employee.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable_employee.getColumnModel().getColumn(3).setPreferredWidth(15);
            jTable_employee.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable_employee.getColumnModel().getColumn(5).setPreferredWidth(15);
        }

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_employeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_employeeMouseClicked
      actionSelectTable();
    }//GEN-LAST:event_jTable_employeeMouseClicked

    private void bt_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addMouseClicked
        try {
            actionAddEmployee();
        } catch (Exception ex) {
            Logger.getLogger(DefineEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_addMouseClicked

    private void bt_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_updateMouseClicked
        try {
            actionUpdate();
        } catch (Exception ex) {
            Logger.getLogger(DefineEmployee.class.getName()).log(Level.SEVERE, null, ex);
            System.err.println("ddddd");
        }
    }//GEN-LAST:event_bt_updateMouseClicked

    private void bt_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_deleteMouseClicked
        try {
            actionDelete();
        } catch (Exception ex) {
            Logger.getLogger(DefineEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_deleteMouseClicked

    private void bt_add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_add1MouseClicked
      resetTx();
    }//GEN-LAST:event_bt_add1MouseClicked

    public void actionSelectTable(){
        int row = jTable_employee.getSelectedRow();
      tx_name.setText(jTable_employee.getModel().getValueAt(row, 4).toString());
      name = jTable_employee.getModel().getValueAt(row, 4).toString();
      tx_age.setText(jTable_employee.getModel().getValueAt(row, 3).toString());
      tx_adress.setText(jTable_employee.getModel().getValueAt(row, 2).toString());
      tx_phone.setText(jTable_employee.getModel().getValueAt(row, 1).toString());
      tx_email.setText(jTable_employee.getModel().getValueAt(row, 0).toString());
    }
    public void resetTx(){
        tx_name.setText(null);
      tx_age.setText(null);
      tx_adress.setText(null);
      tx_phone.setText(null);
      tx_email.setText(null);
    }
    public void actionAddEmployee() throws Exception{
        String name = tx_name.getText().toString();
        int Age = Integer.parseInt(tx_age.getText().toString());
        String Adress = tx_adress.getText().toString();
        String Phone = tx_phone.getText().toString();
        String Email = tx_email.getText().toString();
        
        emp.addEmployee(name, Age, Adress, Phone, Email, jTable_employee);
        resetTx();
    }
    public void actionUpdate() throws Exception{
        if(name != null){
       int oldID=  inf.getIDForTRX("Employee", name);
       String newName =tx_name.getText().toString();
       int newAge =Integer.parseInt( tx_age.getText().toString());
       String Adress = tx_adress.getText().toString();
       String Phone = tx_phone.getText().toString();
       String Email =tx_email.getText().toString();
            resetTx();
      // emp.updateEmployee( int oldID,newName, newAge, Adress, Phone,Email, jTable_employee);
       emp.updateEmployee(oldID, newName, newAge, Adress, Phone, Email, jTable_employee);
        } else {
            JOptionPane.showMessageDialog(this,"You must Select row in the table");
        }
    }
    public void actionDelete () throws Exception{
        int oldID=  inf.getIDForTRX("Employee", name);
        //emp.deleteProduct(oldID, jTable_employee);
        emp.deleteEmployee(oldID, jTable_employee);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefineEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefineEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefineEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefineEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DefineEmployee().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DefineEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_add1;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_employee;
    private javax.swing.JTextField tx_adress;
    private javax.swing.JTextField tx_age;
    private javax.swing.JTextField tx_email;
    private javax.swing.JTextField tx_name;
    private javax.swing.JTextField tx_phone;
    // End of variables declaration//GEN-END:variables
}
