/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBTables.FillComboBox;
import DBTables.TableINF;
import DBTables.WareHouseLine;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MR
 */
public class DefineProductGroupINWarehouse extends javax.swing.JFrame {

    /**
     * Creates new form DefineProductGroupINWarehouse
     */
    WareHouseLine wl;
    TableINF inf;
    FillComboBox fill;
    String SelectedPG;
    String SelectedWH;
    public DefineProductGroupINWarehouse() throws Exception {
        initComponents();
        wl = new WareHouseLine();
        inf = new TableINF();
        fill = new FillComboBox();
        fill.fillCB(CB_Warehouse,"name" , "warehouse");
         fill.fillCB(CB_productGroup,"name" , "ProductGroup");
        wl.Show_user_inTable(TableWarehouseLine);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CB_productGroup = new javax.swing.JComboBox();
        CB_Warehouse = new javax.swing.JComboBox();
        bt_add = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableWarehouseLine = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("إضافة مجموعات الأصناف إلي المخزن");
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("أسم المخزن");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("إضافة مجموعة أصناف له");

        CB_productGroup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB_productGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CB_Warehouse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB_Warehouse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bt_add.setBackground(new java.awt.Color(255, 102, 0));
        bt_add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_add.setText("إضافة صنف للمخزن");
        bt_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addMouseClicked(evt);
            }
        });

        bt_update.setBackground(new java.awt.Color(255, 102, 0));
        bt_update.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_update.setText("تعديل الصنف");
        bt_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_updateMouseClicked(evt);
            }
        });

        bt_delete.setBackground(new java.awt.Color(255, 102, 0));
        bt_delete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bt_delete.setText("حذف صنف من المخزن");
        bt_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_deleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bt_delete)
                        .addGap(84, 84, 84)
                        .addComponent(bt_update)
                        .addGap(73, 73, 73)
                        .addComponent(bt_add)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CB_Warehouse, 0, 305, Short.MAX_VALUE)
                            .addComponent(CB_productGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(74, 74, 74))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CB_Warehouse, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CB_productGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_add)
                    .addComponent(bt_update)
                    .addComponent(bt_delete))
                .addGap(29, 29, 29))
        );

        getContentPane().add(jPanel2);

        TableWarehouseLine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "يحتوي علي مجموعة أصناف", "إسم المخزن", "م"
            }
        ));
        TableWarehouseLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableWarehouseLineMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableWarehouseLine);
        if (TableWarehouseLine.getColumnModel().getColumnCount() > 0) {
            TableWarehouseLine.getColumnModel().getColumn(0).setPreferredWidth(100);
            TableWarehouseLine.getColumnModel().getColumn(1).setPreferredWidth(100);
            TableWarehouseLine.getColumnModel().getColumn(2).setPreferredWidth(15);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableWarehouseLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableWarehouseLineMouseClicked
        actionTableSelected();
    }//GEN-LAST:event_TableWarehouseLineMouseClicked

    private void bt_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_updateMouseClicked
        try {
            actionUpdateSelected();
        } catch (Exception ex) {
            Logger.getLogger(DefineProductGroupINWarehouse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_updateMouseClicked

    private void bt_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_deleteMouseClicked
        try {
            actionDeleteSelected();
        } catch (Exception ex) {
            Logger.getLogger(DefineProductGroupINWarehouse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_deleteMouseClicked

    private void bt_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addMouseClicked
        try {
            actionAddSelected();
        } catch (Exception ex) {
            Logger.getLogger(DefineProductGroupINWarehouse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_addMouseClicked

     public void actionTableSelected(){
       int row = TableWarehouseLine.getSelectedRow();
       CB_Warehouse.setSelectedItem(TableWarehouseLine.getModel().getValueAt(row, 1));
       SelectedWH = TableWarehouseLine.getModel().getValueAt(row, 1).toString();
       CB_productGroup.setSelectedItem(TableWarehouseLine.getModel().getValueAt(row,0));
       SelectedPG =TableWarehouseLine.getModel().getValueAt(row, 0).toString();
       
 }
     
     public void actionUpdateSelected() throws SQLException, Exception{
         int IDWHold = inf.getIDForTRX("Warehouse", SelectedWH);
         int IDWHnew = inf.getIDForTRX("Warehouse", CB_Warehouse.getSelectedItem().toString());
         int IDPGold = inf.getIDForTRX("ProductGroup", SelectedPG);
         int IDPGnew = inf.getIDForTRX("ProductGroup", CB_productGroup.getSelectedItem().toString());
         int ID = inf.getIDLineForTRX("warehouseLine",IDWHold ,IDPGold);
        wl.updateWarehouseLine(IDWHnew, IDPGnew, ID, TableWarehouseLine);
     }
     
     public void actionDeleteSelected() throws SQLException, Exception{
         int IDWH = inf.getIDForTRX("Warehouse", SelectedWH);
         int IDPG = inf.getIDForTRX("ProductGroup", SelectedPG);
         int ID = inf.getIDLineForTRX("warehouseLine",IDWH ,IDPG);
         wl.DeleteWarehouseLine(ID, TableWarehouseLine);
     }
     
     public void actionAddSelected() throws SQLException, Exception{
          
         String WH = CB_Warehouse.getSelectedItem().toString();
        int WHID= inf.getIDForTRX("warehouse", WH);
         String PG = CB_productGroup.getSelectedItem().toString();
         int PGID = inf.getIDForTRX("productgroup", PG);
         wl.addWarehouseLine(WHID, PGID, TableWarehouseLine);
     }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefineProductGroupINWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefineProductGroupINWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefineProductGroupINWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefineProductGroupINWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DefineProductGroupINWarehouse().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DefineProductGroupINWarehouse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB_Warehouse;
    private javax.swing.JComboBox CB_productGroup;
    private javax.swing.JTable TableWarehouseLine;
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
