/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBTables.FillComboBox;
import DBTables.Product;
import DBTables.TableINF;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MR
 */
public class DefineProduct extends javax.swing.JFrame {

    /**
     * Creates new form DefineProductnew
     */
    Product pd ;
     FillComboBox fill;
      String SelectedProduct ,SelectedUOM ,SelectedUOMSale,SelectedDescription;
      double SelectedPrice ,SelectedPriceSale;
      TableINF inf ;
      int Search =0;
     
    public DefineProduct() throws Exception {
        initComponents();
        this.setSize(1000, 700);
        this.setLocationRelativeTo(null);
         pd = new Product();
         inf = new TableINF();
         fill =new FillComboBox();
         
         fill.fillCB(CB_pgroup, "name", "productGroup");
         fill.fillCB(CB_UOM1, "name", "UOM");
         fill.fillCB(CB_UOMSales, "name", "UOM");
       try{ 
           pd.Show_user_inTable(jTable_product);
       } 
       catch(Exception e){System.err.println("Error :");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_product = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tx_product = new javax.swing.JTextField();
        CB_pgroup = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tx_code = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_priceSales = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tx_description = new javax.swing.JTextField();
        b_add = new javax.swing.JButton();
        b_update = new javax.swing.JButton();
        b_Delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tx_UOMPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CB_UOM1 = new javax.swing.JComboBox();
        CB_UOMSales = new javax.swing.JComboBox();
        bt_reenter = new javax.swing.JButton();
        tx_QTY = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tx_QTYWH = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tx_QTYRemaining = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("تعريف منتجات");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTable_product.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ملاحظات", "المتبقي في المخزن", "الكمية المباعة", "سعر وحدة البيع", "وحدة البيع", "الكمية المخزنة", "الوحدة", "سعر الوحدة", "الصنف", "الكود", "مجموعة أصناف", "م"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_product.setRowHeight(30);
        jTable_product.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jTable_product.setSelectionForeground(new java.awt.Color(51, 255, 51));
        jTable_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_product);
        if (jTable_product.getColumnModel().getColumnCount() > 0) {
            jTable_product.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTable_product.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable_product.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable_product.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable_product.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTable_product.getColumnModel().getColumn(6).setPreferredWidth(40);
            jTable_product.getColumnModel().getColumn(7).setPreferredWidth(30);
            jTable_product.getColumnModel().getColumn(9).setPreferredWidth(30);
            jTable_product.getColumnModel().getColumn(11).setPreferredWidth(10);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("مجموعة أصناف");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("الصنف");

        tx_product.setBackground(new java.awt.Color(108, 122, 137));
        tx_product.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_product.setForeground(new java.awt.Color(255, 255, 255));
        tx_product.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_product.setSelectionColor(new java.awt.Color(255, 153, 51));

        CB_pgroup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB_pgroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "مشروبات ساخنة", "مشروبات غازية", "مشروبات باردة" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("الكود");

        tx_code.setBackground(new java.awt.Color(108, 122, 137));
        tx_code.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_code.setForeground(new java.awt.Color(255, 255, 255));
        tx_code.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_code.setSelectionColor(new java.awt.Color(255, 153, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("سعر البيع");

        tx_priceSales.setBackground(new java.awt.Color(108, 122, 137));
        tx_priceSales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_priceSales.setForeground(new java.awt.Color(255, 255, 255));
        tx_priceSales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_priceSales.setSelectionColor(new java.awt.Color(255, 153, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("الملاحظات");

        tx_description.setBackground(new java.awt.Color(108, 122, 137));
        tx_description.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_description.setForeground(new java.awt.Color(255, 255, 255));
        tx_description.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_description.setSelectionColor(new java.awt.Color(255, 153, 51));

        b_add.setBackground(new java.awt.Color(255, 102, 0));
        b_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_add.setText("إضافة منتج");
        b_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_addMouseClicked(evt);
            }
        });

        b_update.setBackground(new java.awt.Color(255, 102, 0));
        b_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_update.setText("تعديل منتج");
        b_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_updateMouseClicked(evt);
            }
        });

        b_Delete.setBackground(new java.awt.Color(255, 102, 0));
        b_Delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_Delete.setText("حذف منتج");
        b_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_DeleteMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("وحدة التخزين");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("سعر الوحدة");

        tx_UOMPrice.setBackground(new java.awt.Color(108, 122, 137));
        tx_UOMPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_UOMPrice.setForeground(new java.awt.Color(255, 255, 255));
        tx_UOMPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_UOMPrice.setSelectionColor(new java.awt.Color(255, 153, 51));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("وحدة البيع");

        CB_UOM1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB_UOM1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CB_UOMSales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB_UOMSales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bt_reenter.setBackground(new java.awt.Color(255, 102, 0));
        bt_reenter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_reenter.setText("إعادة إدخال");
        bt_reenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reenterActionPerformed(evt);
            }
        });

        tx_QTY.setBackground(new java.awt.Color(108, 122, 137));
        tx_QTY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_QTY.setForeground(new java.awt.Color(255, 255, 255));
        tx_QTY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_QTY.setSelectionColor(new java.awt.Color(255, 153, 51));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("الكمية المباعة");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("كمية الوحدات المخزنة");

        tx_QTYWH.setBackground(new java.awt.Color(108, 122, 137));
        tx_QTYWH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_QTYWH.setForeground(new java.awt.Color(255, 255, 255));
        tx_QTYWH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_QTYWH.setSelectionColor(new java.awt.Color(255, 153, 51));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setText("All");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        tx_QTYRemaining.setBackground(new java.awt.Color(108, 122, 137));
        tx_QTYRemaining.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tx_QTYRemaining.setForeground(new java.awt.Color(255, 255, 255));
        tx_QTYRemaining.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_QTYRemaining.setSelectionColor(new java.awt.Color(255, 153, 51));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("المتبقي في المخزن");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_reenter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(CB_pgroup, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tx_product, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tx_QTY, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(tx_QTYWH, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(tx_QTYRemaining))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tx_description, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tx_UOMPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                            .addComponent(tx_priceSales))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tx_code, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CB_UOM1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(CB_UOMSales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b_Delete)
                        .addGap(27, 27, 27)
                        .addComponent(b_update)
                        .addGap(18, 18, 18)
                        .addComponent(b_add)
                        .addGap(168, 168, 168))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CB_pgroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_reenter)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(tx_UOMPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_UOM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tx_QTYWH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tx_priceSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CB_UOMSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tx_QTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tx_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tx_QTYRemaining, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_add)
                    .addComponent(b_update)
                    .addComponent(b_Delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productMouseClicked
        actionTableSelected();
    }//GEN-LAST:event_jTable_productMouseClicked

    private void b_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_addMouseClicked
        try {
            actionAddSelected();
            reset();
            getSearcResultFor();
            
        } catch (Exception ex) {
            Logger.getLogger(DefineProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_addMouseClicked

    private void bt_reenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reenterActionPerformed
        reset();
    }//GEN-LAST:event_bt_reenterActionPerformed

    private void b_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_DeleteMouseClicked
      int ID;
        try {
            ID = inf.getIDForTRX("product", SelectedProduct);
             pd.deleteProduct(ID, jTable_product);
        } catch (SQLException ex) {
            Logger.getLogger(DefineProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(DefineProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_b_DeleteMouseClicked

    private void b_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_updateMouseClicked
        try {
            int ID = inf.getIDForTRX("product", SelectedProduct);
            int IDUOM = inf.getIDForTRX("UOM", CB_UOM1.getSelectedItem().toString());
            int IDUOMSale =inf.getIDForTRX("UOM", CB_UOMSales.getSelectedItem().toString());
            int row = jTable_product.getSelectedRow();
            String NewName = tx_product.getText().toString();
            String NewCode = tx_code.getText().toString();
             String StPriceSale  =  tx_priceSales.getText().toString();
             double NewPriceSale = Double.parseDouble(StPriceSale);
              String NewUOMPrice = tx_UOMPrice.getText().toString();
              String  NewDescription =tx_description.getText().toString();
              System.out.println(""+NewDescription);
          double newSelectedPrice =  Double.parseDouble(NewUOMPrice);
          double QTY = Double.parseDouble(tx_QTY.getText().toString());
          double QTYWH = Double.parseDouble(tx_QTYWH.getText().toString());
           double QTYRemaining = Double.parseDouble(tx_QTYRemaining.getText().toString());
             pd.updateProduct(ID,NewName,NewCode,newSelectedPrice,IDUOM,NewPriceSale,IDUOMSale,NewDescription,QTY,QTYWH,QTYRemaining,jTable_product);
       
        } catch (SQLException ex) {
            Logger.getLogger(DefineProduct.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(DefineProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_b_updateMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            Search = 1;
            getSearcResultFor();
            
        } catch (Exception e) {
            System.err.println(""+e);
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {Search=0;
            getSearcResultFor();
            
        } catch (Exception ex) {
            Logger.getLogger(DefineProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

     public void actionTableSelected(){
          int row = jTable_product.getSelectedRow();
           CB_pgroup.setSelectedItem(jTable_product.getModel().getValueAt(row,10).toString()); 
          tx_code.setText( jTable_product.getModel().getValueAt(row,9).toString());
        tx_product.setText( jTable_product.getModel().getValueAt(row,8).toString());
         SelectedProduct = jTable_product.getModel().getValueAt(row,8).toString().toString();
         tx_UOMPrice.setText( jTable_product.getModel().getValueAt(row,7).toString());
          String StUOMPrice = jTable_product.getModel().getValueAt(row,7).toString();
          SelectedPrice =  Double.parseDouble(StUOMPrice);
             CB_UOM1.setSelectedItem(jTable_product.getModel().getValueAt(row,6).toString());
         SelectedUOM=jTable_product.getModel().getValueAt(row,6).toString();
          tx_QTYWH.setText( jTable_product.getModel().getValueAt(row,5).toString());
           CB_UOMSales.setSelectedItem(jTable_product.getModel().getValueAt(row,4).toString());
           SelectedUOMSale = jTable_product.getModel().getValueAt(row,4).toString();
       tx_priceSales.setText( jTable_product.getModel().getValueAt(row,3).toString());
       String StPriceSale  =   jTable_product.getModel().getValueAt(row,3).toString();
       //  System.out.println("StPriceSale :"+StPriceSale);      
       SelectedPriceSale = Double.parseDouble(StPriceSale);
       tx_QTY.setText(jTable_product.getModel().getValueAt(row,2).toString());
        tx_QTYRemaining.setText( jTable_product.getModel().getValueAt(row,1).toString());
         tx_description.setText( jTable_product.getModel().getValueAt(row,0).toString());
         SelectedDescription =jTable_product.getModel().getValueAt(row,0).toString();
         
    }
    public void reset(){
         tx_product.setText(null);
         tx_code.setText(null);
         tx_UOMPrice.setText(null);
         tx_priceSales.setText(null);
         tx_description.setText(null);
         tx_QTY.setText(null);
    }
    public void actionAddSelected() throws SQLException, Exception{
        int PGID = inf.getIDForTRX("ProductGroup",CB_pgroup.getSelectedItem().toString() );
        String Product = tx_product.getText().toString();
        double price =Double.parseDouble(tx_UOMPrice.getText().toString()) ;
        int UOM_ID = inf.getIDForTRX("UOM", CB_UOM1.getSelectedItem().toString());
        String Code = tx_code.getText().toString();
        String Description = tx_description.getText().toString();
        int SalesUOM_ID = inf.getIDForTRX("UOM", CB_UOMSales.getSelectedItem().toString());
        double salesPrice = Double.parseDouble(tx_priceSales.getText().toString());
         double QTY = Double.parseDouble(tx_QTY.getText().toString());
          double QTYWH = Double.parseDouble(tx_QTYWH.getText().toString());
          double QTYRemianing = Double.parseDouble(tx_QTYRemaining.getText().toString());
        pd.addProduct(PGID, Product, price, UOM_ID, Code, Description, SalesUOM_ID, salesPrice, QTY,QTYWH,QTYRemianing,jTable_product);
    }
    
    public void getSearcResultFor() throws SQLException, Exception{
        
         if (Search == 0){
            pd.Show_user_inTable(jTable_product);
        }else if (Search == 1)
        {
          int ID = inf.getIDForTRX("ProductGroup", CB_pgroup.getSelectedItem().toString());
        String sqlLike = "";
        if (tx_product.getText().toString().equals(null)){
            
        }else {
            sqlLike = " and name like '%"+tx_product.getText().toString()+"%'";
        }
        pd.Show_SearcedPG_inTable(ID,sqlLike, jTable_product);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefineProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefineProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefineProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefineProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DefineProduct().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DefineProduct.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB_UOM1;
    private javax.swing.JComboBox CB_UOMSales;
    private javax.swing.JComboBox CB_pgroup;
    private javax.swing.JButton b_Delete;
    private javax.swing.JButton b_add;
    private javax.swing.JButton b_update;
    private javax.swing.JButton bt_reenter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_product;
    private javax.swing.JTextField tx_QTY;
    private javax.swing.JTextField tx_QTYRemaining;
    private javax.swing.JTextField tx_QTYWH;
    private javax.swing.JTextField tx_UOMPrice;
    private javax.swing.JTextField tx_code;
    private javax.swing.JTextField tx_description;
    private javax.swing.JTextField tx_priceSales;
    private javax.swing.JTextField tx_product;
    // End of variables declaration//GEN-END:variables
}
