/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DBConnect.Connector;
import DBTables.Tables;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author MR
 */
public class OrderTRX extends javax.swing.JPanel {

    /**
     * Creates new form OrderTRX
     */
     private static State viewState;
    public OrderTRX(State st) throws Exception {
        initComponents();
        panTRX.removeAll();
        createTablesButtons();
         UpdatePanTRX(st);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panOrderTRXhead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panTRXButtons = new javax.swing.JPanel();
        panTRX = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(2, 1));

        panOrderTRXhead.setBackground(new java.awt.Color(204, 204, 255));
        panOrderTRXhead.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 255)));
        panOrderTRXhead.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("         ");
        panOrderTRXhead.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setText("       ");
        panOrderTRXhead.add(jLabel2, java.awt.BorderLayout.LINE_END);

        jLabel3.setText("   ");
        panOrderTRXhead.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jLabel4.setText("          ");
        panOrderTRXhead.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        panTRXButtons.setLayout(new java.awt.GridLayout(1, 0));
        panOrderTRXhead.add(panTRXButtons, java.awt.BorderLayout.CENTER);

        add(panOrderTRXhead);

        panTRX.setBackground(new java.awt.Color(204, 204, 255));
        panTRX.setLayout(new java.awt.BorderLayout());
        add(panTRX);
    }// </editor-fold>//GEN-END:initComponents
public void createTablesButtons() throws Exception{
    Tables t = new Tables();
    int tno = t.getTablesNo();
    String sqlTableName = "select T_TableNo_ID  name ,STATUS from T_TableNo  order by T_TableNo_ID";
   ResultSet rs = new Connector().start_Statment().executeQuery(sqlTableName);
    while(rs.next()){
    
    JButton [] TableButtons= new JButton[tno] ;
    
        String name=""+rs.getInt("name");
         JButton btn=new JButton(name);
         if(rs.getString("STATUS").equals("N")){
             btn.setBackground(Color.GREEN);
         }else {
             btn.setBackground(Color.RED);
         }
                panTRXButtons.add(btn);
        
    }
    rs.close();
}
public void refreshTables() throws Exception{
    panTRXButtons.removeAll();
    createTablesButtons();
    panTRXButtons.repaint();
    panTRXButtons.revalidate();
    panOrderTRXhead.removeAll();
    panOrderTRXhead.repaint();
    panOrderTRXhead.revalidate();
    
    
}
public void UpdatePanTRX(State viewState){
   
                //System.out.println("change state: " + viewState);

                switch (viewState) {
                case Home_STATE:
                        panTRX.removeAll();
                        panTRX.setBackground(Color.yellow);
                        panTRX.revalidate();
                        panTRX.repaint();
                        
                        break;
                case Warehouse_STATE:
                        panTRX.removeAll();
                        Panwharehouse pw = new Panwharehouse();
                        panTRX.add(pw);
                        panTRX.revalidate();
                        panTRX.repaint();
                        break;
                default:
                        System.out.println("UNKNOWN STATE!");
                        break;
                }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panOrderTRXhead;
    private javax.swing.JPanel panTRX;
    private javax.swing.JPanel panTRXButtons;
    // End of variables declaration//GEN-END:variables
}
